<a href="https://colab.research.google.com/github/claudiodanielpc/medium/blob/main/portal_datos_abiertos_cdmx.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import requests
import pandas as pd
from bs4 import BeautifulSoup
from matplotlib import pyplot as plt
import matplotlib.dates as mdates
from dateutil.rrule import rrule, MONTHLY
from matplotlib.ticker import FixedLocator
from math import floor

In [2]:
headers={'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/134.0.0.0 Safari/537.36'}
##Url básica del portal de datos abiertos
url_basica="https://datos.cdmx.gob.mx/api/3/action/"

In [3]:
#Nombre de los conjuntos de datos
url_datos=url_basica+"package_list"

nom_conjunto=requests.get(url_datos, headers=headers)
nom_conjunto=nom_conjunto.json()
nom_conjunto=nom_conjunto['result']
print("Total de conjuntos de datos:", len(nom_conjunto))

Total de conjuntos de datos: 475

In [4]:
##Obtener datos generales de cada conjunto de datos
titulo = []
organizacion= []
descripcion = []
frecuencia=[]
metadata_creado=[]
metadata_modificado=[]
url_ultimo_archivo=[]


#Buscar
for conjunto in nom_conjunto:
    url_datos=url_basica+"package_show?id="+conjunto
    r=requests.get(url_datos, headers=headers)
    r=r.json()
    titulo.append(r['result']['title'])
    descripcion.append(r['result']['notes'])
    organizacion.append(r['result']['organization']['title'])
    recursos = r['result'].get('resources', [])
    if recursos:
      freq = recursos[0].get('update_frequency', None)
      original_url = recursos[0].get('original_url', None)
    else:
      freq = None
      original_url = None
    frecuencia.append(freq)
    url_ultimo_archivo.append(original_url)
    metadata_creado.append(r['result'].get('metadata_created'))
    metadata_modificado.append(r['result'].get('metadata_modified'))

In [5]:
tabla_conjunto = pd.DataFrame({
    "nombre": titulo,
    "organizacion": organizacion,
    "descripcion": descripcion,
    "frecuencia": frecuencia,
    "metadata_creado": metadata_creado,
    "metadata_modificado": metadata_modificado,
    "url_ultimo_archivo": url_ultimo_archivo
})

tabla_conjunto = tabla_conjunto.apply(lambda x: x.astype(str).str.lower())
#Eliminar acentos
tabla_conjunto = tabla_conjunto.apply(lambda x: x.str.replace('á', 'a').str.replace('é', 'e').str.replace('í', 'i').str.replace('ó', 'o').str.replace('ú', 'u'))
#Eliminar espacios adelante y atrás
tabla_conjunto = tabla_conjunto.apply(lambda x: x.str.strip())

#Variables fecha_creacion y fecha_ult_modif en formato fecha
tabla_conjunto['metadata_creado'] = pd.to_datetime(tabla_conjunto['metadata_creado'], format='%Y-%m-%dT%H:%M:%S.%f')

tabla_conjunto['metadata_modificado'] = pd.to_datetime(tabla_conjunto['metadata_modificado'], format='%Y-%m-%dT%H:%M:%S.%f')
print("Total de conjuntos extraídos:", len(tabla_conjunto))
tabla_conjunto

Total de conjuntos extraídos: 475

,nombre,organizacion,descripcion,frecuencia,metadata_creado,metadata_modificado,url_ultimo_archivo
0,solicitudes *0311,agencia digital de innovacion publica (adip),**descripcion**\r\n\r\nel conjunto de datos de...,mensual,2022-10-05 21:53:24.039621,2024-04-01 20:13:31.531809,https://datos.cdmx.gob.mx/dataset/529aac27-d1c...
1,accidentes terrestres en las alcaldias,instituto de planeacion democratica y prospectiva,accidentes terrestres en las alcaldias,none,2022-01-27 20:03:18.319830,2023-02-15 00:58:46.488348,none
2,acciones sociales vigentes en la ciudad de mexico,consejo de evaluacion del desarrollo social de...,la **politica de desarrollo social** en la ciu...,,2021-01-13 04:21:39.740771,2023-02-15 00:57:03.472691,none
3,actas de defuncion en el registro civil de la ...,direccion general del registro civil,este conjunto de datos tiene como objetivo rep...,trimestral,2021-01-13 04:36:48.558579,2024-01-09 17:35:21.395624,none
4,acueducto planta chapultepec,instituto de planeacion democratica y prospectiva,trazo del acueducto planta chapultepec,none,2022-02-01 21:59:15.157067,2023-02-15 00:59:05.471381,https://datos.cdmx.gob.mx/dataset/09d5e844-3eb...
...,...,...,...,...,...,...,...
470,zonas de patrullaje (cuadrantes) 2018,secretaria de seguridad ciudadana (ssc),este es el directorio de zonas de patrullaje v...,,2021-01-13 04:07:19.450907,2023-07-07 18:17:27.362877,none
471,zonas para impulsar la vivienda para trabajado...,instituto de planeacion democratica y prospectiva,zonas para impulsar y facilitar la construccio...,none,2022-02-01 18:20:17.325613,2023-02-15 00:57:56.178684,none
472,municipios de las zonas metropolitanas en la z...,instituto de planeacion democratica y prospectiva,delimitacion de los municipios de las zonas me...,none,2022-02-02 19:42:13.487964,2023-02-15 00:56:50.546012,none
473,zonas de monumentos historicos,instituto de planeacion democratica y prospectiva,poligono de las zonas declaradas patrimonio po...,none,2022-02-02 19:45:02.253397,2023-02-15 00:58:01.413896,https://datos.cdmx.gob.mx/dataset/b3bdbaef-ced...
474,zonificacion sismica por colonia,instituto de planeacion democratica y prospectiva,definicion de colonias segun su grado de pelig...,none,2022-03-18 16:42:34.421170,2023-02-15 00:57:39.476250,none

In [6]:
tabla_conjunto["frecuencia"].unique()

array(['mensual', 'none', '', 'trimestral', 'historico', 'semestral',
       'anual', 'bimestral', 'semanal'], dtype=object)

In [8]:
pd.DataFrame({
    "frecuencia": tabla_conjunto["frecuencia"].value_counts(dropna=False).index,
    "numero": tabla_conjunto["frecuencia"].value_counts(dropna=False).values,
    "porcentaje": tabla_conjunto["frecuencia"].value_counts(normalize=True, dropna=False).mul(100).round(2).values
}).sort_values("numero", ascending=False)

   frecuencia  numero  porcentaje
0        none     222       46.74
1                 121       25.47
2   historico      43        9.05
3       anual      36        7.58
4     mensual      29        6.11
5  trimestral      15        3.16
6   semestral       6        1.26
7   bimestral       2        0.42
8     semanal       1        0.21

In [9]:
pd.DataFrame({
    "frecuencia": tabla_conjunto["organizacion"].value_counts(dropna=False).index,
    "numero": tabla_conjunto["organizacion"].value_counts(dropna=False).values,
    "porcentaje": tabla_conjunto["organizacion"].value_counts(normalize=True, dropna=False).mul(100).round(2).values
}).sort_values("numero", ascending=False)

                                           frecuencia  numero  porcentaje
0   instituto de planeacion democratica y prospectiva     205       43.16
1        agencia digital de innovacion publica (adip)      50       10.53
2                    secretaria de movilidad (semovi)      34        7.16
3   secretaria de gestion integral de riesgos y pr...      22        4.63
4       secretaria de administracion y finanzas (saf)      21        4.42
5              secretaria del medio ambiente (sedema)      20        4.21
6   instituto nacional de estadistica y geografia ...      17        3.58
7                                 secretaria de salud      15        3.16
8   consejo de evaluacion del desarrollo social de...      15        3.16
9             secretaria de seguridad ciudadana (ssc)      10        2.11
10                              secretaria de turismo       9        1.89
11        secretaria de desarrollo economico (sedeco)       6        1.26
12  secretaria de inclusion y bienestar social (si...       5        1.05
13  secretaria de desarrollo urbano y vivienda (se...       5        1.05
14  fiscalia general de justicia (fgj) de la ciuda...       5        1.05
15               direccion general del registro civil       4        0.84
16                    comision para la reconstruccion       4        0.84
17  secretaria de pueblos y barrios originarios y ...       4        0.84
18                          secretaria de las mujeres       4        0.84
19  secretaria de trabajo y fomento al empleo (styfe)       3        0.63
20         instituto electoral de la ciudad de mexico       3        0.63
21  centro de comando, control, computo, comunicac...       2        0.42
22   sistema de aguas de la ciudad de mexico (sacmex)       2        0.42
23  secretaria de educacion ciencia y tecnologia e...       2        0.42
24                                  correos de mexico       1        0.21
25                              instituto del deporte       1        0.21
26  coordinacion general del gabinete de seguridad...       1        0.21
27  procuraduria ambiental y del ordenamiento terr...       1        0.21
28   instituto de verificacion administrativa (invea)       1        0.21
29                                      metrobus (mb)       1        0.21
30               autoridad del centro historico (ach)       1        0.21
31        sistema de transporte colectivo (stc) metro       1        0.21

In [10]:
pd.DataFrame({
    "frecuencia": tabla_conjunto[tabla_conjunto["organizacion"] ==
                                 "instituto de planeacion democratica y prospectiva"]["frecuencia"]
                    .value_counts(dropna=False).index,

    "numero": tabla_conjunto[tabla_conjunto["organizacion"] ==
                              "instituto de planeacion democratica y prospectiva"]["frecuencia"]
                    .value_counts(dropna=False).values,

    "porcentaje": tabla_conjunto[tabla_conjunto["organizacion"] ==
                                 "instituto de planeacion democratica y prospectiva"]["frecuencia"]
                    .value_counts(normalize=True, dropna=False).mul(100).round(2).values
}).sort_values("numero", ascending=False)

   frecuencia  numero  porcentaje
0        none     199       97.07
1                   3        1.46
2  trimestral       2        0.98
3   historico       1        0.49

In [7]:
hoy = pd.Timestamp.today()
fin_2025 = pd.Timestamp("2025-12-31")

df = tabla_conjunto.copy()

df["metadata_modificado"] = pd.to_datetime(df["metadata_modificado"], errors="coerce")

frecuencia_dias = {
    "mensual": 30,
    "trimestral": 90,
    "semestral": 182,
    "anual": 365,
    "bimestral": 60,
    "semanal": 7,
    "histórico": None,
    "none": None
}

df["dias_esperados"] = df["frecuencia"].map(frecuencia_dias)

# --- Número de actualizaciones faltantes ---
df["num_actualizaciones_faltantes"] = df.apply(
    lambda row: (
        floor((hoy - row["metadata_modificado"]).days / row["dias_esperados"])
        if pd.notna(row["metadata_modificado"]) and pd.notna(row["dias_esperados"])
        else 0
    ),
    axis=1
)

df[
    df["frecuencia"].isin(["mensual", "trimestral", "semestral", "anual", "bimestral", "semanal"])
][[
    "nombre",
    "frecuencia",
    "metadata_modificado",
    "num_actualizaciones_faltantes"
]].sort_values("num_actualizaciones_faltantes", ascending=False).head(40)

,nombre,frecuencia,metadata_modificado,num_actualizaciones_faltantes
394,servicios integrales de locatel,semanal,2023-05-30 19:02:40.476607,131
124,datos de bicicletas (ecobici),mensual,2023-05-25 22:23:21.777969,30
271,matrimonios registrados en la ciudad de mexico,mensual,2023-07-07 18:31:41.771040,29
374,red de meteorologia y radiacion solar (redmet),mensual,2023-06-29 00:44:44.307060,29
370,red automatica de monitoreo atmosferico (rama),mensual,2023-06-28 22:27:25.210881,29
281,nacimientos registrados en la ciudad de mexico,mensual,2023-07-07 18:37:22.504725,29
371,red de recarga externa de la tarjeta de movili...,mensual,2023-07-06 22:08:47.293664,29
244,ingresos del sistema de transporte colectivo m...,mensual,2023-09-02 02:53:05.782118,27
106,convocatorias de licitaciones publicas y anunc...,mensual,2023-12-04 22:11:41.449975,24
379,remuneraciones al personal de la ciudad de mexico,mensual,2024-02-08 19:53:49.830072,22
373,red manual de monitoreo atmosferico (redma),mensual,2024-02-23 21:08:04.963655,21
224,incidentes viales reportados por c5,mensual,2024-03-08 00:46:07.280858,21
213,hechos de transito registrados por la ssc (ser...,mensual,2024-03-11 23:02:25.940916,21
382,reportes de agua,mensual,2024-04-01 19:15:36.245521,20
0,solicitudes *0311,mensual,2024-04-01 20:13:31.531809,20
164,catalogo de datos abiertos de la cdmx,mensual,2024-05-13 16:54:01.201534,19
409,tarjeta de movilidad integrada en el transport...,mensual,2024-09-12 19:28:28.571522,15
203,gasto hecho por turistas en la ciudad de mexico,mensual,2024-09-03 17:45:52.295310,15
263,llegada de extranjeros al aicm,mensual,2024-09-03 17:43:10.591057,15
293,ocupacion hotelera en la ciudad de mexico,mensual,2024-09-03 17:47:51.238941,15
8,viajes del sistema ecobici,mensual,2024-08-26 22:44:55.308363,15
426,turistas en la ciudad de mexico,mensual,2024-09-03 17:40:59.301348,15
257,juzgados civicos (infractores),bimestral,2023-07-07 22:21:43.627536,14
299,padrón de proveedores vigente de la ciudad de...,mensual,2024-10-23 20:35:25.357327,13
449,victimas en carpetas de investigacion fgj,mensual,2024-10-15 23:29:25.620027,13
50,biciestacionamientos,trimestral,2023-06-12 22:53:15.069797,10
62,carpetas de investigacion fgj,mensual,2025-03-06 18:53:25.262476,9
32,atenciones de abogadas de las mujeres,trimestral,2023-07-07 22:29:22.975974,9
140,depositos vehiculares,trimestral,2023-07-10 21:35:07.501092,9
381,reporte estadistico de la ciudad de mexico,trimestral,2023-12-19 19:27:27.809284,7
389,sistemas de captacion de agua de lluvia,bimestral,2024-08-26 18:09:18.624863,7
245,ingresos de parquimetros,trimestral,2024-03-04 22:13:24.897622,7
212,hechos de transito registrados por la ssc 2024...,mensual,2025-05-02 19:37:25.269066,7
17,app cdmx,trimestral,2024-01-09 16:32:07.837985,7
3,actas de defuncion en el registro civil de la ...,trimestral,2024-01-09 17:35:21.395624,7
290,nombres registrados en actas del registro civil,semestral,2023-05-04 18:53:44.239646,5
280,muevete en bici,trimestral,2024-08-14 21:09:16.847576,5
243,ingresos de la ciudad de mexico,trimestral,2024-08-06 21:20:15.592488,5
122,cumplimiento de fotocivicas,trimestral,2024-08-01 16:00:51.241072,5
76,cicloestaciones ecobici (nuevo sistema),trimestral,2024-10-17 18:42:18.494365,4