<a href="https://colab.research.google.com/github/claudiodanielpc/medium/blob/main/rezago_r_srvyr.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [24]:
##Borrar datos del entorno
rm(list=ls())


#Se utiliza pacman para instalar y cargar paquetes
if(!require('pacman')) install.packages('pacman')
pacman::p_load(tidyverse,janitor,srvyr)

Loading required package: pacman

In [25]:
# -------------------------------
# Datos de viviendas ENIGH 2024
# -------------------------------
url_vivi <- "https://www.inegi.org.mx/contenidos/programas/enigh/nc/2024/microdatos/enigh2024_ns_viviendas_csv.zip"

In [26]:
# -------------------------------
# Descargar ZIP
# -------------------------------
zip_path <- "enigh2024_viviendas.zip"
download.file(
  url_vivi,
  destfile = zip_path,
  mode = "wb"
)
# -------------------------------
# Crear carpeta destino
# -------------------------------
output_dir <- "enigh2024_viviendas"
dir.create(output_dir, showWarnings = FALSE)

In [27]:
# -------------------------------
# Descomprimir
# -------------------------------
unzip(zip_path, exdir = output_dir)

# Ver archivos
list.files(output_dir)

[1] "viviendas.csv"

In [32]:
## Leer viviendas
viviendas <- read_csv(paste0(output_dir,"/viviendas.csv"))

valor_excusado <- if (length(unique(viviendas$excusado)) == 3) 3 else 2
viviendas<-viviendas%>%
  janitor::clean_names()%>%
  #Formato de variables clave para rezago
  mutate(
    across(
      starts_with("mat") & where(is.character),
      ~ replace_na(parse_number(.x, na = c('', 'NA', '&')), 0)
    ),
    across(
      starts_with("mat") & where(is.numeric),
      ~ replace_na(.x, 0)
    ),
    ##Identificador de rezago
    rezago = if_else(
      ((tot_resid / num_cuarto) > 2.5) |
        (mat_pared %in% 1:6) |
        (mat_techos %in% c(1:4, 6, 7, 9)) |
        (mat_pisos == 1) |
        (excusado == valor_excusado),
      "En rezago",
      "Fuera de rezago"
    ),
    ##Clave de entidad
    cve_ent = case_when(
      nchar(folioviv) == 9  ~ paste0("0", substr(folioviv, 1, 1)),
      nchar(folioviv) == 10 ~ substr(folioviv, 1, 2)
    ),
    #Crear nombre de entidad
    nom_ent=case_when(
      cve_ent == "01" ~ "Aguascalientes",
      cve_ent == "02" ~ "Baja California",
      cve_ent == "03" ~ "Baja California Sur",
      cve_ent == "04" ~ "Campeche",
      cve_ent == "05" ~ "Chiapas",
      cve_ent == "06" ~ "Chihuahua",
      cve_ent == "07" ~ "Coahuila",
      cve_ent == "08" ~ "Colima",
      cve_ent == "09" ~ "Ciudad de México",
      cve_ent == "10" ~ "Durango",
      cve_ent == "11" ~ "Guanajuato",
      cve_ent == "12" ~ "Guerrero",
      cve_ent == "13" ~ "Hidalgo",
      cve_ent == "14" ~ "Jalisco",
      cve_ent == "15" ~ "México",
      cve_ent == "16" ~ "Michoacán",
      cve_ent == "17" ~ "Morelos",
      cve_ent == "18" ~ "Nayarit",
      cve_ent == "19" ~ "Nuevo León",
      cve_ent == "20" ~ "Oaxaca",
      cve_ent == "21" ~ "Puebla",
      cve_ent == "22" ~ "Querétaro Arteaga",
      cve_ent == "23" ~ "Quintana Roo",
      cve_ent == "24" ~ "San Luis Potosí",
      cve_ent == "25" ~ "Sinaloa",
      cve_ent == "26" ~ "Sonora",
      cve_ent == "27" ~ "Tabasco",
      cve_ent == "28" ~ "Tamaulipas",
      cve_ent == "29" ~ "Tlaxcala",
      cve_ent == "30" ~ 	"Veracruz",
      cve_ent == "31" ~ "Yucatán",
      cve_ent == "32" ~ "Zacatecas",
      TRUE 	~ NA_character_
    ))

Warning message:
“One or more parsing issues, call `problems()` on your data frame for details,
e.g.:
  dat <- vroom(...)
  problems(dat)”
Rows: 90324 Columns: 82
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (8): folioviv, mat_techos, finan_8, num_dueno1, num_dueno2, ubica_geo, ...
dbl (74): tipo_viv, mat_pared, mat_pisos, antiguedad, antigua_ne, cocina, co...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

In [33]:
##Crear diseño muestral

dm <- viviendas %>%
    as_survey_design(ids = upm, strata = est_dis, weights = factor)

In [34]:
##Calcular total de viviendas

dm%>%
  summarise(viviendas=survey_total(vartype=c("se","ci","cv")))

  viviendas viviendas_se viviendas_low viviendas_upp viviendas_cv
1 38356042  142516.3     38076681      38635403      0.003715616

In [35]:
##Calcular rezago habitacional general

dm%>%
  group_by(rezago)%>%
  summarise(viviendas=survey_total(vartype=c("se","ci","cv")))

  rezago          viviendas viviendas_se viviendas_low viviendas_upp
1 En rezago        8381545  106629.1      8172530       8590560
2 Fuera de rezago 29974497  144400.9     29691442      30257552
  viviendas_cv
1 0.01272189
2 0.00481746

In [36]:
##Calcular rezago habitacional por entidad federativa
dm%>%
  group_by(rezago, nom_ent)%>%
  summarise(viviendas=survey_total(vartype=c("se","ci","cv")))

   rezago          nom_ent             viviendas viviendas_se viviendas_low
1  En rezago       Aguascalientes        16755    2076.157     12685.31
2  En rezago       Baja California      474035   23282.208    428397.12
3  En rezago       Baja California Sur   58987    3828.600     51482.16
4  En rezago       Campeche             115596    4870.217    106049.38
5  En rezago       Chiapas               88072    7561.688     73249.55
6  En rezago       Chihuahua             54659    2865.524     49041.99
7  En rezago       Ciudad de México     182009   17552.150    147603.21
8  En rezago       Coahuila            1010514   40909.787    930322.48
9  En rezago       Colima               441301   18699.856    404645.47
10 En rezago       Durango              106894    8827.075     89591.13
11 En rezago       Guanajuato           221803   14532.863    193315.62
12 En rezago       Guerrero             484667   19271.557    446890.82
13 En rezago       Hidalgo              157728   11221.246    135732.07
14 En rezago       Jalisco              196356   20091.024    156973.50
15 En rezago       Michoacán            385276   27715.182    330948.59
16 En rezago       Morelos              114985    6545.302    102154.87
17 En rezago       México               533829   37542.682    460237.69
18 En rezago       Nayarit               80646    5321.247     70215.27
19 En rezago       Nuevo León           106370   11873.701     83095.13
20 En rezago       Oaxaca               608586   25169.846    559247.97
21 En rezago       Puebla               403118   29641.034    345015.53
22 En rezago       Querétaro Arteaga     76539    5693.533     65378.51
23 En rezago       Quintana Roo          74772    5659.762     63677.71
24 En rezago       San Luis Potosí      135358    9549.815    116638.42
25 En rezago       Sinaloa               78259    7422.145     63710.08
26 En rezago       Sonora               263290   16528.481    230890.81
27 En rezago       Tabasco              472099   17060.913    438656.13
28 En rezago       Tamaulipas           129401    9003.561    111752.18
29 En rezago       Tlaxcala              34795    2649.892     29600.67
30 En rezago       Veracruz            1090501   48189.784    996039.20
⋮  ⋮               ⋮                   ⋮         ⋮            ⋮
35 Fuera de rezago Baja California Sur  216172    4542.414     207267.9
36 Fuera de rezago Campeche             154931    5267.518     144605.6
37 Fuera de rezago Chiapas              922606   13729.662     895693.1
38 Fuera de rezago Chihuahua            187165    3460.481     180381.8
39 Fuera de rezago Ciudad de México    2847715   41689.768    2765994.6
40 Fuera de rezago Coahuila             517048   28855.348     460485.6
41 Fuera de rezago Colima               775057   17123.347     741491.7
42 Fuera de rezago Durango              425858   10491.800     405291.9
43 Fuera de rezago Guanajuato          1525015   24092.792    1477788.2
44 Fuera de rezago Guerrero             506138   19921.685     467087.4
45 Fuera de rezago Hidalgo              806497   28363.205     750899.3
46 Fuera de rezago Jalisco             2426311   44114.277    2339838.0
47 Fuera de rezago Michoacán           1022595   32976.544     957954.2
48 Fuera de rezago Morelos              483051   11810.611     459899.8
49 Fuera de rezago México              4505633   69002.646    4370373.7
50 Fuera de rezago Nayarit              304695    5979.482     292974.0
51 Fuera de rezago Nuevo León          1737413   24247.679    1689882.6
52 Fuera de rezago Oaxaca               587979   23286.600     542332.5
53 Fuera de rezago Puebla              1461936   32086.427    1399040.1
54 Fuera de rezago Querétaro Arteaga    664786   14409.847     636539.8
55 Fuera de rezago Quintana Roo         515512    9019.315     497832.3
56 Fuera de rezago San Luis Potosí      698457   14110.396     670797.7
57 Fuera de rezago Sinaloa              861439   14043.260     833911.3
58 Fuera de rezago Sonora               678306   17055.666     644873.4
59 Fuera de rezago Tabasco              268140    9737.738     249052.0
60 Fuera de rezago Tamaulipas           978389   15985.035     947055.1
61 Fuera de rezago Tlaxcala             366227    6288.343     353900.6
62 Fuera de rezago Veracruz            1403376   58922.449    1287876.0
63 Fuera de rezago Yucatán              608008   11363.234     585733.7
64 Fuera de rezago Zacatecas            389200    9438.158     370699.3
   viviendas_upp viviendas_cv
1    20824.69    0.12391269
2   519672.88    0.04911496
3    66491.84    0.06490582
4   125142.62    0.04213137
5   102894.45    0.08585803
6    60276.01    0.05242548
7   216414.79    0.09643562
8  1090705.52    0.04048414
9   477956.53    0.04237438
10  124196.87    0.08257784
11  250290.38    0.06552149
12  522443.18    0.03976247
13  179723.93    0.07114302
14  235738.50    0.10231938
15  439603.41    0.07193592
16  127815.13    0.05692310
17  607420.31    0.07032717
18   91076.73    0.06598277
19  129644.87    0.11162640
20  657924.03    0.04135791
21  461220.47    0.07352942
22   87699.49    0.07438735
23   85866.29    0.07569360
24  154077.58    0.07055227
25   92807.92    0.09484079
26  295689.19    0.06277671
27  505541.87    0.03613842
28  147049.82    0.06957876
29   39989.33    0.07615727
30 1184962.80    0.04419050
⋮  ⋮             ⋮
35  225076.1     0.02101296
36  165256.4     0.03399912
37  949518.9     0.01488139
38  193948.2     0.01848893
39 2929435.4     0.01463973
40  573610.4     0.05580787
41  808622.3     0.02209302
42  446424.1     0.02463685
43 1572241.8     0.01579840
44  545188.6     0.03936018
45  862094.7     0.03516839
46 2512784.0     0.01818163
47 1087235.8     0.03224790
48  506202.2     0.02445003
49 4640892.3     0.01531475
50  316416.0     0.01962448
51 1784943.4     0.01395620
52  633625.5     0.03960448
53 1524831.9     0.02194790
54  693032.2     0.02167592
55  533191.7     0.01749584
56  726116.3     0.02020224
57  888966.7     0.01630209
58  711738.6     0.02514450
59  287228.0     0.03631587
60 1009722.9     0.01633812
61  378553.4     0.01717062
62 1518876.0     0.04198622
63  630282.3     0.01868928
64  407700.7     0.02425015